### ISSUE TITLE
JSON-LD serving is broken 

### ISSUE THREAD

**Issue by VladimirAlexiev** [opencitations/oc_meta#11]
https://w3id.org/oc/meta/ra/0610116006.json, https://opencitations.net/meta/ra/0610116006.json return `internal server error`

All of these return data:
- https://opencitations.net/meta/ra/0610116006.html
- https://opencitations.net/meta/ra/0610116006.ttl
- https://opencitations.net/meta/ra/0610116006.rdf

**Comment by ivanhb** [comment]
Now it should work!
