### ISSUE TITLE
duplicated Identifier value objects

### ISSUE THREAD

**Issue by VladimirAlexiev** [opencitations/oc_meta#12]
https://opencitations.net/meta/ra/0610116006.html shows 5 identifiers:

https://w3id.org/oc/meta/id/0610136876
https://w3id.org/oc/meta/id/06103454749
https://w3id.org/oc/meta/id/06203462349
https://w3id.org/oc/meta/id/06303470667

However, all of these `Identifier` value objects are the same, representing `crossref:297`.
Is it possible to clean up these duplicates?

**Comment by arcangelo7** [comment]
I am aware of this problem. I have already written [the software that solves it](https://github.com/opencitations/oc_meta/blob/master/oc_meta/run/fixer/duplicated_ids.py) and am currently testing it. As soon as the problem is solved, I will update the triplestore, and the dumps and notify you

**Comment by arcangelo7** [comment]
The bug has now been fixed
